using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PpmSharp.ShaderGen;

[Generator(LanguageNames.CSharp)]
public sealed class ShaderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var shaderFiles = context.AdditionalTextsProvider
            .Where(file => 
            {
                var ext = Path.GetExtension(file.Path).ToLowerInvariant();
                return ext is ".vert" or ".frag" or ".glsl";
            })
            .Select((file, ct) => 
            {
                var content = file.GetText(ct)?.ToString() ?? string.Empty;
                var fileName = Path.GetFileNameWithoutExtension(file.Path);
                var extension = Path.GetExtension(file.Path).TrimStart('.');
                return (FileName: fileName, Extension: extension, Content: content);
            });

        var allShaders = shaderFiles.Collect();

        context.RegisterSourceOutput(allShaders, (spc, shaders) =>
        {
            if (shaders.Length == 0)
                return;

            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine();
            sb.AppendLine("namespace PpmSharp.Generated;");
            sb.AppendLine();
            sb.AppendLine("public static class Shaders");
            sb.AppendLine("{");

            foreach (var shader in shaders)
            {
                var propertyName = ToPascalCase(shader.FileName) + ToPascalCase(shader.Extension);
                var escapedContent = EscapeString(shader.Content);

                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// Shader source from {shader.FileName}.{shader.Extension}");
                sb.AppendLine($"    /// </summary>");
                sb.AppendLine($"    public const string {propertyName} = @\"{escapedContent}\";");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            spc.AddSource("Shaders.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in input)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpper(c) : c);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        return sb.ToString();
    }

    private static string EscapeString(string input)
    {
        return input.Replace("\"", "\"\"");
    }
}